version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mbox-lite-linux-amd64
    main: ./cmd/mbox
    binary: mbox-lite
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    tags: &tags
      - nogateway,nowebdav,nocos,nobos,nohdfs,noibmcos,noobs,nooss,noqingstor,nosftp,noswift,noazure,nogs,noufile,nob2,nonfs,nodragonfly,nomysql,nopg,notikv,nobadger,noetcd,nocifs,notrace,nometrics,nos3
    ldflags: &ldflags
      - -s -w -X github.com/revv00/mailfs/pkg/version.Revision={{.ShortCommit}} -X github.com/revv00/mailfs/pkg/version.RevisionDate={{.Date}}

  - id: mbox-lite-linux-arm64
    main: ./cmd/mbox
    binary: mbox-lite
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    tags: *tags
    ldflags: *ldflags

  - id: mbox-lite-windows-amd64
    main: ./cmd/mbox
    binary: mbox-lite
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CGO_CFLAGS=-I./include/fuse
    goos:
      - windows
    goarch:
      - amd64
    tags: *tags
    ldflags: *ldflags

  - id: mbox-lite-darwin-amd64
    main: ./cmd/mbox
    binary: mbox-lite
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
    goos:
      - darwin
    goarch:
      - amd64
    tags: *tags
    ldflags: *ldflags

  - id: mbox-lite-darwin-arm64
    main: ./cmd/mbox
    binary: mbox-lite
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
    goos:
      - darwin
    goarch:
      - arm64
    tags: *tags
    ldflags: *ldflags

archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}{{ if .IsNightly }}_nightly{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: revv00
    name: mailfs
